server:
  port: 8085

spring:

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_service
    username: training
    password: training

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret-key: authserviceapijwtsecret5367566B59703373367639792F423FD5A71347437
    token-duration: 1D

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
    health:
      show-details: always
