server:
  port: 8111

spring:
  cloud.gateway.mvc:
    routesMap:
      configRoute1:
        uri: lb://account-service
        predicates:
          - Path=/bankingapp/api/accounts/**
          - Method=GET,POST,PUT,DELETE
        filters:
          - StripPrefix=2
      configRoute2:
        uri: lb://transaction-service
        predicates:
          - Path=/bankingapp/api/transactions/**
          - Method=GET,POST,PUT,DELETE
        filters:
          - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"