server:
  port: 8084

spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  file:
    name: logs/notification.log
  level:
    com.lowes.bankingapp: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
